name: ngabsen
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  dropdown_search: ^2.0.1
  http: 0.13.4
  flutter: 
    sdk: flutter
  dio: ^4.0.3
  animated_splash_screen: ^1.1.0
  get_storage: ^2.0.3
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 600
          style: italic